---
settings:
  name: Astra Trident
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '22.04'
    url: "/trident-2204"
  - version-number: '23.07'
    url: "/trident"
  - version-number: '22.01'
    url: "/trident-2201"
  - version-number: '21.10'
    url: "/trident-2110"
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de Astra Trident
    url: "/index.html"
  - title: Notas de la versión
    url: "/trident-rn.html"
  - section: trident-concepts
  - section: trident-get-started
  - section: trident-managing-k8s
  - section: trident-use
  - section: trident-docker
  - title: Preguntas frecuentes
    url: "/faq.html"
  - title: Soporte técnico
    url: "/get-help.html"
  - title: Resolución de problemas
    url: "/troubleshooting.html"
  - section: trident-reco
  - section: trident-reference
  - title: Versiones anteriores
    url: "/earlier-versions.html"
  - title: Avisos legales
    url: "/legal.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Notas de la versión
      url: trident-rn.html
    - title: Introducción a Astra Trident
      url: "/trident-concepts/intro.html"
    - title: Requisitos de Astra Trident
      url: "/trident-get-started/requirements.html"
    - title: Pruébelo
      url: "/trident-get-started/quickstart.html"
    - title: PREGUNTAS FRECUENTES
      url: "/faq.html"
  - title: Ponga en marcha Astra Trident
    links:
    - title: Realice puestas en marcha con el operador de Trident
      url: "/trident-get-started/kubernetes-deploy-operator.html"
    - title: Despliegue con trimentctl
      url: "/trident-get-started/kubernetes-deploy-tridentctl.html"
    - title: Ponga en marcha Astra Trident para Docker
      url: "/trident-docker/deploy-docker.html"
  - title: Actualice Astra Trident
    links:
    - title: Actualice con el operador Trident
      url: "/trident-managing-k8s/upgrade-operator.html"
    - title: Actualice con trimentctl
      url: "/trident-managing-k8s/upgrade-tridentctl.html"
  - title: Utilice Astra Trident
    links:
    - title: Configurar los back-ends
      url: "/trident-use/backends.html"
    - title: Cree back-ends con kubectl
      url: "/trident-use/backend-kubectl.html"
    - title: Pasar entre las opciones de administración del back-end
      url: "/trident-use/backend_options.html"
    - title: Gestione las clases de almacenamiento
      url: "/trident-use/manage-stor-class.html"
    - title: Realizar operaciones de volumen
      url: "/trident-use/vol-operations.html"
    - title: Supervisión de Astra Trident
      url: "/trident-use/monitor-trident.html"
  - title: Demostraciones y tutoriales
    links:
    - title: Vídeos de Astra Trident
      url: https://tv.netapp.com/detail/video/5995831475001/using-trident-with-kubernetes
  - title: Blogs y comunidad
    links:
    - title: Blogs de Astra
      url: https://cloud.netapp.com/blog/topic/astra
    - title: Blogs de Astra Trident
      url: https://netapp.io/persistent-storage-provisioner-for-kubernetes/
    - title: Kubernetes Hub
      url: https://cloud.netapp.com/kubernetes-hub
    - title: NetApp.io
      url: https://netapp.io/
    - title: Slack
      url: https://netapppub.slack.com/
product-family:
  name: Astra
  repo: astra-family
